[build]
  command = """
    curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.9-stable.tar.xz -o flutter.tar.xz
    tar xf flutter.tar.xz
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter doctor
    flutter pub get
    flutter build web --release --base-href /
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.16.9"

[[plugins]]
  package = "netlify-plugin-flutter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 