[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter doctor
    flutter pub get
    flutter build web --release --base-href /
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.19.0"

[[plugins]]
  package = "netlify-plugin-flutter"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 